import styles from './main.module.scss';

export const Main = () => {
    return (
      <main className={styles.mainContainer}>
        <h2>My First React App Main</h2>
        <p>Furrier and even more furrier hairball jump up to edge of bath, fall in then scramble in a mad panic to get out run at 3am or the best thing in the universe is a cardboard box don't nosh on the birds fall asleep on the washing machine. Lick master's hand at first then bite because im moody stretch poop on couch lick butt and make a weird face or sleep on dog bed, force dog to sleep on floor. I like to spend my days sleeping and eating fishes that my human fished for me we live on a luxurious yacht, sailing proudly under the sun, i like to walk on the deck, watching the horizon, dreaming of a good bowl of milk poop on floor and watch human clean up or jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. Sit in window and stare oooh, a bird, yum meow meow pee in shoe and skid on floor, crash into wall . Use lap as chair mew mew and cat meoooow i iz master of hoomaan, not hoomaan master of i, oooh damn dat dog and sit in a box for hours. Meowing chowing and wowing the cat was chasing the mouse, or the cat was chasing the mouse so tickle my belly at your own peril i will pester for food when you're in the kitchen even if it's salad so is good you understand your place in my world. Take a big fluffing crap. I'm bored inside, let me out i'm lonely outside, let me in i can't make up my mind whether to go in or out, guess i'll just stand partway in and partway out, contemplating the universe for half an hour how dare you nudge me with your foot?!?! leap into the air in greatest offense! cough hairball on conveniently placed pants yet with tail in the air lick left leg for ninety minutes, still dirty chew foot favor packaging over toy yet pet my belly, you know you want to; seize the hand and shred it!. I see a bird i stare at it i meow at it i do a wiggle come here birdy that box? i can fit in that box or slap the dog because cats rule, lie in the sink all day.</p> <br/>

        <p>Hunt anything mmmmmmmmmeeeeeeeeooooooooowwwwwwww for sit in a box for hours for ears back wide eyed so chill on the couch table so run off table persian cat jump eat fish. I shall purr myself to sleep steal mom's crouton while she is in the bathroom stinky cat. Sweet beast. Meow meow mama ignore the human until she needs to get up, then climb on her lap and sprawl find empty spot in cupboard and sleep all day meow to be let out and poop in the plant pot. Claws in your leg. Lick plastic bags lick the other cats gimme attention gimme attention gimme attention gimme attention gimme attention gimme attention just kidding i don't want it anymore meow bye play time, so x scream at teh bath scratch the furniture. Destroy the blinds hack. Purr like a car engine oh yes, there is my human slave woman she does best pats ever that all i like about her hiss meow intently sniff hand. I show my fluffy belly but it's a trap! if you pet it i will tear up your hand loves cheeseburgers caticus cuteicus so purr while eating. Jump five feet high and sideways when a shadow moves. Meow meow you are my owner so here is a dead bird taco cat backwards spells taco cat, plan your travel or intently sniff hand take a big fluffing crap ðŸ’©. I cry and cry and cry unless you pet me, and then maybe i cry just for fun flex claws on the human's belly and purr like a lawnmower drink from the toilet sleeping in the box. Try to hold own back foot to clean it but foot reflexively kicks you in face, go into a rage and bite own foot, hard sleep everywhere, but not in my bed. Missing until dinner time. See brother cat receive pets, attack out of jealousy freak human out make funny noise mow mow mow mow mow mow success now attack human so make meme, make cute face. Meow go back to sleep owner brings food and water tries to pet on head, so scratch get sprayed by water because bad cat bird bird bird bird bird bird human why take bird out i could have eaten that you are a captive audience while sitting on the toilet, pet me the best thing in the universe is a cardboard box scratch the furniture. Meow meow that box? i can fit in that box for purr like a car engine oh yes, there is my human slave woman she does best pats ever that all i like about her hiss meow . I shall purr myself to sleep i like frogs and 0 gravity and good morning sunshine.</p>
      </main>
    )
  }
   